### ISSUE TITLE
Handling Android orientation in surface rotation tutorial

### ISSUE THREAD

**Issue by PavelRudko-ARM** [KhronosGroup/Vulkan-Samples#113]
A code snippet in the [surface rotation tutorial](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/performance/surface_rotation/surface_rotation_tutorial.md#rotation-in-android) suggests using `APP_CMD_CONTENT_RECT_CHANGED` to handle orientation changes. 
However, this event is never generated by the current version of NDK without some extra work which is done in the framework (using `onContentRectChanged`).
This is not mentioned in the tutorial, so the advice is a little bit misleading (see this [issue](https://github.com/ARM-software/vulkan_best_practice_for_mobile_developers/issues/36)).
Probably it is good to add a little **Note** section with an explanation.
This NDK [issue](https://github.com/android/ndk/issues/1139) is already reported and it's very likely that it will be fixed in the version 22, so it would be good to keep in mind (and probably update the code and the tutorial).

**Comment by TomAtkinsonArm** [comment]
[Here](https://android-review.googlesource.com/c/platform/ndk/+/1180321/3/sources/android/native_app_glue/android_native_app_glue.c#386) is the fixed callback in the ndk version 22. We could add a note and say this is fixed in NDK 22.

Another option would be to implement this method and its supporting methods and add it to the onContentRectChanged callback if the callback is currently NULL. The note would then be that we have implemented a fix for older ndks to mimic the functionality of future versions

Currently using NDK version 20 the following callbacks are null in android_main:
- OnNativeWindowResize
- OnNativeWindowRedrawNeeded
- OnContentRectChanged

**Comment by TomAtkinsonArm** [comment]
This said after reviewing both the ndk implementation and the `on_content_rect_changed` implementation in this project both methods are effectively doing the same thing
