### ISSUE TITLE
CI failing at documentation steps

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#1219]
It looks like with some recent change (?) instead of just failing the github deployment, the antora doc CI step now also fails for all PRs:

![image](https://github.com/user-attachments/assets/0e1f9c29-da95-45fc-ac9f-40d987b46a02)

No idea how to fix. Any idea @gpx1000, @oddhack ?

Maybe related to the recent merge of #1046?

**Comment by oddhack** [comment]
It's failing because Antora is generating errors, because there are structural problems in its inputs. See e,g, https://github.com/KhronosGroup/Vulkan-Samples/actions/runs/11707802295/job/32608015570 . Hopefully with the errors flagged in CI there is motivation to fix them, because they've been affecting the docs site build for quite a while without action. N.b. this was the whole point of #1046.

**Comment by SaschaWillems** [comment]
Makes sense. But some of the errors seem to be caused by links going to other projects of the documentation site like the guide. They don't seem to be wrong, but seem to fail because e.g. the guide isn't available in this repo?

For those that are obviously wrong I'll try to fix them.

**Comment by gpx1000** [comment]
I'm working on a fix now

**Comment by oddhack** [comment]
We might have to conditionally exclude those bits in the single-repo build.

**Comment by gpx1000** [comment]
It's easier to simply do a filter and ignore the errors/warnings that we don't want to kill the build.

**Comment by gpx1000** [comment]
Okay, once #1221 is merged, and we merge #1222 then this issue will be fixed.
