### ISSUE TITLE
Crash on aws T4

### ISSUE THREAD

**Issue by ddesmond** [KhronosGroup/Vulkan-Samples#1225]
Hi all!
I am trying my best to make vulkan work under alma9.4 running a T4 GPU on aws.

Compiles VulkanSDK and Vulkan-Samples succesfully.

Error i am facing now is:
<pre><font color="#FF0000">&gt;</font> ./build/linux/app/bin/Release/x86_64/vulkan_samples sample hdr
[<font color="#00AA00">info</font>] Logger initialized
[<font color="#00AA00">info</font>] Initializing Vulkan sample
[<font color="#00AA00">info</font>] Vulkan debug utils enabled (VK_EXT_debug_utils)
[<font color="#00AA00">info</font>] Extension VK_KHR_get_physical_device_properties2 found, enabling it
[<font color="#00AA00">info</font>] Extension VK_EXT_debug_utils found, enabling it
[<font color="#00AA00">info</font>] Extension VK_KHR_xcb_surface found, enabling it
[<font color="#00AA00">info</font>] Enabled Validation Layers:
[<font color="#00AA00">info</font>] Found GPU: Tesla T4
[<font color="#00AA00">info</font>] Found GPU: llvmpipe (LLVM 17.0.6, 256 bits)
[1]    16715 segmentation fault (core dumped)  ./build/linux/app/bin/Release/x86_64/vulkan_samples sample hdr</pre>

Same happesn when running vkcube.

How can I work around this? Do i miss any dependencies?

thanks for any tip!

**Comment by SaschaWillems** [comment]
Is that a GPU that can actually present? T4 afaik do not have a visual output, and these samples require a queue with presentation support. 

Can you post the callstack that leads up to the segmentation fault?

**Comment by gpx1000** [comment]
@SaschaWillems is correct, the samples here explicitly look for a presentation queue when they are selecting graphics cards.  If you're using AWS then you're likely not interested in a presentation pipeline.  Instead, you'd want to have some form of rendering to texture, if you indeed render anything at all.  If your goal is to simply use the compute pipeline, that is possible and fun way to go.  However, if you're looking for compute, I might recommend pointing out that OpenCL exists and might be better suited for your needs.
If you want to render to a texture, look at how we achieve that here in the samples with batch mode.

**Comment by ddesmond** [comment]
Thanks for quick replies!
My scenario is a workstation setup for 3d aritsts, so I boot RHEL (alma 9 in this case) with fully working xfce desktop environment. I do have gl working and outputing glxgears with vglrun.
I am not interested only in compute but also having the ouput of the demos visulay in the UI - end goal make Unreal5 working since is Vulkan only.

Thanks again!

**Comment by ddesmond** [comment]
> Is that a GPU that can actually present? T4 afaik do not have a visual output, and these samples require a queue with presentation support.
> 
> Can you post the callstack that leads up to the segmentation fault?

How can I work around this?

**Comment by SaschaWillems** [comment]
You can't. If the GPU has no present queue, you can't run Vulkan applications that require present.

But it's all guess work. Can you post a callstack that leads up to the seg fault, so we can see where it crashes?

**Comment by gpx1000** [comment]
The technologies you list, VGL is a virtualization backend.  What's happening there is it renders to a background texture on the remote machine, then transfers it to your local machine and renders the texture.  The architecture you're using is described pretty well here:
https://virtualgl.org/About/Background

This is possible with Vulkan just as it is with OpenGL.  You need to build a render to texture pipeline remotely on the server, render what you want using the server's GPU, transfer the texture back to the client, then locally, build a normal present pipeline which will display the transferred texture.  I am unaware of any off the shelf solutions which will do this for you off the top of my head, but they might exist.

**Comment by ddesmond** [comment]
Here is my strace output:
[trace.log](https://github.com/user-attachments/files/17708267/trace.log)

Any help is really appreciated.

**Comment by ddesmond** [comment]
> The technologies you list, VGL is a virtualization backend. What's happening there is it renders to a background texture on the remote machine, then transfers it to your local machine and renders the texture. The architecture you're using is described pretty well here: https://virtualgl.org/About/Background
> 
> This is possible with Vulkan just as it is with OpenGL. You need to build a render to texture pipeline remotely on the server, render what you want using the server's GPU, transfer the texture back to the client, then locally, build a normal present pipeline which will display the transferred texture. I am unaware of any off the shelf solutions which will do this for you off the top of my head, but they might exist.

I understand.

My task here is not to write an app itself, but be able to run vulkan-enabled apps in the workstation GUI.
This is why i went and compiled the SDK and the samples to have some kind of baseline since vkcube is also crashing the same way.

**Comment by ddesmond** [comment]
Here is the output of Caps viewer for T4, and support presentation is red false.
![image](https://github.com/user-attachments/assets/9768f0c9-6686-47a7-acda-686a48135a6f)

**Comment by gpx1000** [comment]
It sounds like you're looking for a Virtualization application for Vulkan.  I don't know of any off the top of my head.  You might find luck with a software Vulkan driver which can report itself to the Vulkan Loader.  It then would need to behave exactly as mentioned above.  I don't know what products exist out there in the marketplace, there might be some, but it sadly isn't something I think I can help you with.

**Comment by ddesmond** [comment]
> You can't. If the GPU has no present queue, you can't run Vulkan applications that require present.
> 
> But it's all guess work. Can you post a callstack that leads up to the seg fault, so we can see where it crashes?

Did you maybe had the time to check the strace output?

**Comment by gpx1000** [comment]
I did take a look, it crashes but doesn't give a lot more than a report of a crash.  This is kind of expected as it is a developer's sample repository instead of an end user's tool.  There's plenty of places where the project assumes an uncaught throw of an exception is the correct behavior.  That uncaught exception would show a debug breakpoint in any IDE, while simply report as an exception in the user's environment.  The strace shows that it got up to querying the GPUS:
write(1, "[\33[32minfo\33[m] Found GPU: Tesla "..., 35[info] Found GPU: Tesla T4
) = 35
sysinfo({uptime=562, loads=[4704, 37984, 31392], totalram=33163759616, freeram=18481618944, sharedram=30973952, bufferram=2768896, totalswap=0, freeswap=0, procs=972, totalhigh=0, freehigh=0, mem_unit=1}) = 0
write(1, "[\33[32minfo\33[m] Found GPU: llvmpi"..., 59[info] Found GPU: llvmpipe (LLVM 17.0.6, 256 bits)
) = 59
then the next place it reports is here:
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
[1]    3268 segmentation fault  strace ./build/linux/app/bin/Release/x86_64/vulkan_samples sample hdr

alma /apps/vulkansamples/Vulkan-Samples                          SEGV py lsiopy

Naturally, this isn't a callstack, nor is it the core that was dumped so there's no further debugging magic anyone could do from the strace.  It won't help diagnose the crash itself.  However, I'd go so far as to say it's doing exactly what we expect it to do in the case of not finding a GPU with a present capability on it given that all of the samples are built with the assumption that they can submit a frame to be rendered.
You need a present queue to render something.  A similar environment where you have a remote GPU that's running on another computer could be seen with OpenXR which provides developers with Vulkan without providing direct support for the developer to submit to a present queue directly; nor require a developer to handle anything about the hardware.  There the runtime provides the correct queue to the developer and handles the presentation.  That's probably not what you want.  You want a virtualized driver which will provide a queue that can capture a present queue submission of a frame and redirect it to a texture which can be sent to the client and let the client render rather than something that will provide you with a command buffer you can submit to a present queue as in OpenXR.  Sorry, nothing we can do here.

**Comment by ddesmond** [comment]
Thanks for the exhaustive info GPX :)
