### ISSUE TITLE
Buffer map and unmap seems no longer necessary on MacOS

### ISSUE THREAD

**Issue by tatsy** [KhronosGroup/Vulkan-Samples#187]
I found that some samples such as `texture_loading` is not working on MacOS with latest Vulkan SDK (1.2.148.1). After inspecting on this problem, I finally found that `map` and `unmap` in `vkb::core::Buffer` makes a problem that the host data is not properly transferred to device memory.

I also found that just by commenting out the following line fixes the problem:
https://github.com/KhronosGroup/Vulkan-Samples/blob/d2d68ca7005fd79a908af57527aadf82abf571c9/framework/core/buffer.cpp#L33

My environment is:
* iMac (Retina 5K, 27-inch, 2017)
* MacOS 10.15.6 Catalina
* LunarG Vulkan SDK 1.2.148.1
* Radeon Pro 570 4GB

After reading the comment beside the above line, I wondered if the problem of `map` and `unmap` in MoltenVK has already been resolved, and if so, `vkb::core::Buffer` should be updated such that we can choose keep or disable `VMA_ALLOCATION_CREATE_MAPPED_BIT`.

If the above fix is valid, I am happy to make a PR for that.

**Comment by ghost** [comment]
@billhollings - Can you advise on this issue as well?

**Comment by cdavis5e** [comment]
Starting in 10.15.6 (I think), Metal supports creating linear textures in `Shared` storage. So unmapping isn't necessary starting on 10.15.6. Unfortunately, for 10.15.5 and below, it's still necessary.

**Comment by tatsy** [comment]
@cdavis5e Thank you for your advice. As far as I see the source codes, maybe, there are no option to disable `map` and `unmap` in `vkb::core::Buffer` with MacOS. 

As in the following CMake script, `VK_USE_PLATFORM_MACOS_MVK` is always defined for MacOS. I think it helpful to add a new option to disable `map` and `unmap`.
https://github.com/KhronosGroup/Vulkan-Samples/blob/4eaa13632c426586cfeeb32caf4e450c09d8c345/third_party/CMakeLists.txt#L57

What do you think?

**Comment by billhollings** [comment]
@tatsy 

>What do you think?

What does it mean within the sample code to add a build option to "disable `map` and `unmap`"? On the surface, that sounds like a drastic action.

If you do so, are there alternate paths that will automatically be taken in the sample code, such as staging buffers, etc? But since you reference disabling this in `vkb::core::Buffer`, it sounds like that might impact staging buffers too.

And would the changes apply to all samples, or just select ones that need coherent linear texture memory?

**Comment by tatsy** [comment]
@billhollings I thought that it was almost enough to add a new CMake option such as `VK_USE_PLATFORM_MACOS_NEWER_OSX_15_6` or something like that.

If we do not need to see the minor version of OSX, it can also be detected from `CMAKE_OSX_DEPLOYMENT_TARGET`. However, I am not really sure that only disabling `map` and `unmap` in `vkb::core::Buffer` works fine for all the samples.

**Comment by billhollings** [comment]
>I thought that it was almost enough to add a new CMake option such as VK_USE_PLATFORM_MACOS_NEWER_OSX_15_6 or something like that.

That's possible. But this is a run-time issue. What matters is the run-time environment, not the build environment. So you might build for 10.15.6 and above, but it wouldn't run properly if you actually ran it on earlier OS versions.

I'm also somewhat confused about what the problem is on newer macOS versions. Does the sample not work correctly when avoiding using map and unmap on 10.15.6 and above? If so, do you have more information about what the resulting problem is? If there is a problem not using map and unmap, and it's coming from MoltenVK, then we should fix it.

**Comment by marty-johnson59** [comment]
Ideally, once built, we'd want the sample to run correctly across both old and new OSes.  This implies either a runtime check in the sample, or some kind of fix in MoltenVK (such that the map/unmap required for old OSes doesn't corrupt behavior on new OSes).   Are either of these options a possibility here, or do we need to drop back and include instructions/mechanisms in the sample/framework to disable map/unmap at build time for newer OSes (not preferred)?  Any insights?

**Comment by kvark** [comment]
Vulkan Portability doesn't define any VK_USE_PLATFORM_MACOS_NEWER_OSX_15_6, and vulkan samples should target it (as opposed to MoltenVK specifically).
If this is an issue with Vulkan Portability, let's file an issue there and discuss - https://github.com/KhronosGroup/Vulkan-Portability
Otherwise, this is an issue with MoltenVK and should be moved there - https://github.com/KhronosGroup/MoltenVK

**Comment by gpx1000** [comment]
@marty-johnson59 I tend to agree with @kvark, this is an issue better addressed in either Portability or MoltenVK.  For my two cents, I'd recommend that MoltenVK take a pass at making this a little bit more seamless.  It's probably ok to close this here.

**Comment by marty-johnson59** [comment]
OK, I opened a new issue in MoltenVK (MoltenVK#1327).  Closing this one.  Please refer to that bug moving forward.  Thanks
