### ISSUE TITLE
Compiling on Apple Silicon

### ISSUE THREAD

**Issue by RocketTree** [KhronosGroup/Vulkan-Samples#220]
If you are building on macOS 11.0 on apple silicon you will have issues with it defaulting to arm64.  Until MoltenVK/volk support arm64 you need to force intel64 compilation.

I have got this to work by running cmake with the following commands

`cmake -Bbuild/xcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -G "Xcode"`

Perhaps you could add a note to build.md about this.
Cheers.

**Comment by wasimabbas-arm** [comment]
If you don't mind please submit a PR.

Out of curiosity what issue did you see with Volk and MoltenVK? MoltenVK supports iOS so I would assume it should build fine for arm64 (Assuming you tried it without the SDK which isn't available yet AFAIK).

I would leave the issue open so that we could get to the bottom of why it doesn't work and provide support. Building for `x86_64` on arm64 devices doesn't make sense in the long run.

**Comment by RocketTree** [comment]
I will look into the pull request, my git workflow knowledge isn't the best so I will have to read up on that.

The issue I see is during HelloTriangle::init_instance, the call to `volkInitialize()` fails and it throws `"Failed to initialize volk."`

When compiled intel64 and run under Rosetta 2 it works fine.

I agree this approach does not make sense in the long run.  I am just getting these samples to compile on macOS 11.0/Apple silicon/Rosetta to try and figure out why our engine wont run Vulkan under intel64/Rosetta.

**Comment by gpx1000** [comment]
I did some investigating and want to share my findings.  The tl;dr version is it's probably better simply mandate that Apple Silicon users install CMake 3.19.2 at a minimum for full support.
https://cmake.org/cmake/help/latest/variable/CMAKE_APPLE_SILICON_PROCESSOR.html the `CMAKE_APPLE_SILICON_PROCESSOR` environment variable should be used instead of the `CMAKE_OSX_ARCHITECTURES` or the more general `CMAKE_HOST_SYSTEM_PROCESSOR`. The reasoning for this is on Apple Silicon, the XCode 12 changed the default NATIVE_ARCHS to include both 'arm64' and 'x86_64' which breaks both ninja and make.  The solution that Kitware went with is to force select NATIVE_ARCHS_ACTUAL which allows for only selecting one.  The new build system for XCode was released in the latest CMake.
If you use CMake 3.19.2, there's no longer a requirement for setting any environment variables and all CMake projects should **just build** as normal.
Details can be found here: https://cmake.org/cmake/help/latest/release/3.19.html
