### ISSUE TITLE
What is the expected behaviour of samples that cannot be executed due to unsupported extensions?

### ISSUE THREAD

**Issue by r-potter** [KhronosGroup/Vulkan-Samples#240]
In reviewing #213 and #216, I noted that they have different failure behaviour on devices that don't support the required extensions. 

#213 still ran, but noted that the extension was unsupported and that the checkbox was a no-op (which seemed nice).
#216 failed to start, and logged the missing extension as the cause in the error log (which is what most of the other samples do in this case)

Neither option seems unreasonable, but I wonder if consistency would be a positive here in future?

**Comment by JoseEmilio-ARM** [comment]
The calls to enable a device/instance extension have a second parameter that indicates whether the extension is 'optional'. If it is, the sample will still run and it is responsible for handling the necessary changes to render the scene without using the extension. We found this useful in samples where we wanted to show several features and did not want to crash if just one of them was not supported. In cases where the sample is all about a particular extension, not marking it as optional causes a crash.

In 213 all extensions are marked as optional, whereas in 216 a comment points out that they are not https://github.com/KhronosGroup/Vulkan-Samples/pull/216/files#diff-923f75ffa3930c2a37b4d8b0e84c2b5ac3b14de8bb77bb0027415bf0c9b74fe1R33

I agree that ideally we would never crash (particularly due to a bug on Android where the sample menu does not re-populate), it might be better to introduce some mechanism for samples to have a fallback, for example rendering a message on the screen and letting the user exit.

**Comment by TomAtkinsonArm** [comment]
I have noticed the error handling issues a lot more after it was mentioned in the last call!

The main area of the project that i have run into similar issues is using batch mode and it prematurely closing as an error is thrown when choosing extensions.

Currently we catch runtime errors in the `main` function which means that if an error occurs at any point in a samples execution the entire app will close immediately. This is the behaviour seen in samples where the extension is not present and the application closes. Other than this there is no set in stone fallback.

Adding a fallback to each sample would be a great option but would result in time to review and implement this on older samples. We could implement a failure screen which shows error information and allows for the app to gracefully exit. This would probably take the form of a `VulkanSample` application that only renders the UI with a helpful message such as "extensions XXX not available".

What are your thoughts on future improvements? Are there other options?

**Comment by TomAtkinsonArm** [comment]
Graceful closure implemented in plugins
