### ISSUE TITLE
self-contained samples or better debugger startup integration

### ISSUE THREAD

**Issue by jjYBdx4IL** [KhronosGroup/Vulkan-Samples#268]
Wehn playing around with the samples (ie. using the MSVC Debugger via F5) it is a bit annoying and cumbersome that I have to switch the debugger command arguments every time I want to check a different example in some regard.

I see two solutions: one .exe per sample (who cares about disk space nowadays anyway?). Or using dynamic linking such that vulkan_samples.exe is accessing the samples as DLLs to avoid having to rebuild vulkan_samples.exe.

Or is there a way to tell MSVC to build another target before starting a debugger session?

**Comment by SaschaWillems** [comment]
Splitting the samples into multiple binaries would be a fundamental change, esp. for Android where the samples are run from a unified launcher.

While not a real solution: Are you aware of the [Smart Command Line Arguments Extension](https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments)? It makes it much easier to switch between different command line argument.

**Comment by jjYBdx4IL** [comment]
Using dynamic libs instead of static ones would also help, because then the launcher wouldn't need to be rebuilt and I could just adjust the project generation and set the launcher as debug executable.

**Comment by samwalls-arm** [comment]
Hi there @jjYBdx4IL, currently there are CMake flags for the project which makes it so that each sample builds as its own executable. If I'm working on a single sample, at the very least I find this helps with build times a lot. It might lend itself to your problem too.

If you configure the project with `-DVKB_ENTRYPOINTS=ON`, you'll get cmake targets for each sample. Then build with either `cmake --build my-build-dir --target <sample-name>_app`, or otherwise push the build button for a specific sample project in your IDE of choice.

For further example `cmake --build build/windows --target hello_triangle_app`.

Does this solve your issue? Let us know either way.

**Comment by jjYBdx4IL** [comment]
Not really, but I guess we all have better things to do. Ty!

**Comment by samwalls-arm** [comment]
Hi @jjYBdx4IL could you describe how it doesn't match? I'm just curious because you mentioned that having one .exe per sample might be a solution, and I'm not sure how these differ.

If there's something lacking from the Vulkan-Samples project we're more than happy to consider it.
