### ISSUE TITLE
Raytracing extended pool size

### ISSUE THREAD

**Issue by FilippoLeon** [KhronosGroup/Vulkan-Samples#389]
Maybe I'm missing something, but I think there is an issue with the function
RaytracingExtended::create_descriptor_sets() in raytracing_extended.cpp:

as far as I can tell descriptor_set is allocated from a pool with just 1 one each descriptors in VkDescriptorPoolSize, but it has 7 storage buffers, 26 textures and 1 acceleration structure.

If so, I find weird that the validation layers are not complaining about it.

**Comment by cforfang** [comment]
Guessing slightly here, but looking at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2ab8c47ee56227650422dcd42475888bdc7215a4/layers/descriptor_sets.cpp#L3294 it may look like the layers do not validate the pool is big enough, because it's allowed to _try_ to allocate for a set that overflows the pool capacity. One may question if the layers should then be validating that if you ask for more than is guaranteed, an error is returned though... Seems it currently does not -- i.e. this is a bit of a hole in the layers currently. 

I agree with you the sample is buggy -- it seems the pool size was not increased from how it was set up in `raytracing_basic`  when the sample was expanded.

CC @gpx1000

**Comment by FilippoLeon** [comment]
Guess it make sense that validation do not emit a hard error. Maybe a warning would be in order, but, as you say, it might be out of scope of the validation layers as it is "valid" usage that would  just return an error.

**Comment by gpx1000** [comment]
Wow, great catch!  This is obviously a bug.  I'll get a patch ready for it shortly.  Also, has the issue been created in the validation layers?  It would seem that we should ensure the hole should be raised with the validation layers project.  I'd rather the maintainers there have a chance to decide if there is a hole that should be addressed we inadvertently exposed.

**Comment by FilippoLeon** [comment]
I've created an Issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3510
