### ISSUE TITLE
Fix copyright script

### ISSUE THREAD

**Issue by wasimabbas-arm** [KhronosGroup/Vulkan-Samples#42]
Fix copyright script to check for all contributors copyright year. For example in the following case the script is only checking for the first time.

```
/* Copyright (c) 2018-2020, Arm Limited and Contributors
 * Copyright (c) 2019, Sascha Willems
```

**Comment by wasimabbas-arm** [comment]
@armtomatkinson what do you think about this?

**Comment by TomAtkinsonArm** [comment]
The script implements it with regex so far but explicetely looks for Arm in the expression. Its worth the investigation if it is halting the CI

**Comment by wasimabbas-arm** [comment]
I don't think its halting the CI but we should be able to check for updating all copyright years.

**Comment by TomAtkinsonArm** [comment]
Currently we only check changed files I think. Do we require all copyrights to be {start year}-{present year}

**Comment by TomAtkinsonArm** [comment]
I was mistaken earlier when i said we specifically match for Arm, i was referencing an older revision of the script.

So we just want to update all copyrights instead of the ones in recently changed files?

changing the CI for this would be pointless extra work for the CI as the copyright check is more to check for proper formatted copyrights in new or altered files.

I reckon its going to be a patch correction. download the script. run it on all files. make the relevant changes. push the patch.

**Comment by TomAtkinsonArm** [comment]
And we can also tweak the script to make changes for multiple rows

**Comment by TomAtkinsonArm** [comment]
Just altered the script too look at all cases of copyright. and it flags that the second line is outdated from the test sample you gave above

**Comment by wasimabbas-arm** [comment]
Having a think about this more. Perhaps the copyright notice should only be changed by those working on that part of the code.  So for example Arm did changes should update their copyright but leaving other's intact. Not sure what is the answer to those who does work but are not reflected in copyright. Like people not Arm or Sascha. What would they change?

**Comment by TomAtkinsonArm** [comment]
Merged into the docker image repository
