### ISSUE TITLE
Framework v2.0 warning as error level

### ISSUE THREAD

**Issue by TomAtkinsonArm** [KhronosGroup/Vulkan-Samples#478]
Looking at #320, would it be useful to start framework v2.0 at a specific warning level? I remember windows being quite verbose when bumping the level but this may be a good time to do it

**Comment by gpx1000** [comment]
I completely agree.  The warnings are the compiler's way of yelling at developers before bugs happen.  Ignoring them is both costly and bad practice.  I have found so many massive bugs over the years that are caused by ignoring warnings that for me it drowns out the annoyance in dealing with "no new line at the end of the file" type warnings.

**Comment by SaschaWillems** [comment]
I second that. Though esp. current MSVC versions will spit out lots of errors, even for Vulkan functions, e.g.:

![image](https://user-images.githubusercontent.com/10283127/177530875-10030c04-6169-425f-acb4-0a012b4873fe.png)

So before doing this, we probably need a list of e.g. MSVC specific warnings that we need to disable.

**Comment by TomAtkinsonArm** [comment]
Yeah this is as far as I got the last time we attempted Warnings as Errors for windows. Their higher warnings are a lot stricter than the GCC, Clang counterparts.

I have some time tomorrow to try and do this
