### ISSUE TITLE
Should the validation layer be enabled by default in debug mode?

### ISSUE THREAD

**Issue by asuessenbach** [KhronosGroup/Vulkan-Samples#543]
If so, the [HPP]Instance constructor would require a minor change in one line:

`#ifdef VKB_VALIDATION_LAYERS`    ->    `#if defined(VKB_DEBUG) || defined(VKB_VALIDATION_LAYERS)`

**Comment by SaschaWillems** [comment]
Good question. Tbh I'd prefer them **not** being active by default in debug mode. I usually also don't use the validation build flag, but just start vkconfig and enable validation whenever I need it.

**Comment by gpx1000** [comment]
I think there's value in not requiring debug mode use validation enabled.  The main reason is when we work on extensions that haven't had the VUID changes merged all the way out ahead of a SDK release it would cause an issue as is the case for the mesh shader.  Still having the ability to debug / hit breakpoints when validation hasn't yet promoted is quite useful.

**Comment by asuessenbach** [comment]
@SaschaWillems Any reason why you prefer them not being active by default in debug mode?
@gpx1000 Agreed, when working on samples ahead of the validation layer, you need to disable it. But I think, that's the exceptional case where you could explicitly disable it. Most of the code here is probably covered well by that layer.
After all, I think, having the validation layer on by default in debug mode catches issues before you can think about it. So you can't easily miss them.

**Comment by SaschaWillems** [comment]
It's mostly a personal taste. I rarely use the `VKB_VALIDATION_LAYERS` as toggling it requires an almost full rebuilt. I just prefer to never enable validation in the samples itself but rather fire up VkConfig and enable all validation settings in there.

**Comment by asuessenbach** [comment]
I mean... is there any reason (besides the exceptional case when the sample is ahead of the validation layer) to not enable the validation layer in debug mode?
If it depends on debug mode, you don't have to set VKB_VALIDATION_LAYERS for that case.

**Comment by SaschaWillems** [comment]
Yeah, that's the most obvious reason. If we were to force validation in the debug build, people working on advanced samples where validation is causing problems would have a hard time.

But while we're at the topic: In my samples I choose a completely different way. Validation is enabled at runtime using an argument. Maybe that would be an option for this repo too? Toggling validation using a cmake flag always felt odd for me.

**Comment by gpx1000** [comment]
The current system does work well for my dev setup.  I use an IDE (CLion) and the runtime console arguments easily go into their debug field so turning it on/off is as simple as flipping 1 to 0 when changing the sample name.  I'm fine with a cmake flag, as this can also be toggled rather easily.

I think there's also a deprecation possibility that we should also consider.  Some new vulkan versions could hypothetically deprecate practices on display in certain samples over time.  What is current correct best practice could be deprecated some day from the prescribed best practice.  Obviously, a validation warning would appear correctly but the sample would still run.  In this case, I do like the benefit to us of having an issue brought to attention quickly as it would be a highlighted bug.  However, if the samples are meant as a teaching tool, then there is probably benefit towards keeping the sample simple and keeping the responsibility on the sample developers to keep the current sample in the current best practice.

There's also probably a worthy point to make that as these are samples for teaching, does it make sense to try to encourage validation to be turned on automatically in all vulkan projects as a default for debug mode?  I want to be mindful that what we do here is likely to be copied rather than just the sample itself.

**Comment by SaschaWillems** [comment]
As discussed today we also need to think of Android when doing this. Layers may be pretty outdated on Android devices so and may break with more recent samples. So we need to carefully evaluate this change.

**Comment by SaschaWillems** [comment]
Another thing we need to take into account: Developing new samples for extensions that don't have proper validation layer support. If we were to always enable validation in debug mode, developing such samples would not be possible without manual changes. Not sure if we want that.

**Comment by asuessenbach** [comment]
I think, this can be closed as resolved with the current state.
