### ISSUE TITLE
Consultation on how to use foveated rendering in Vulkan

### ISSUE THREAD

**Issue by andywuchuanlong** [KhronosGroup/Vulkan-Samples#707]
[VK_EXT_fragment_density_map] @mnetsch
Hi mnetsch,

I am very pleased to find your contact information on Vulkan's website. We  need Vulkan to implement foveated rendering. Currently, we only need to implement Fixed Foveated Rendering, We have seen VK_ EXT_ fragment_ density_ Map on Vulkan's website, May I ask if you have any good information on the implementation of foveated rendering that you can provide me with as a reference

**Comment by mnetsch** [comment]
Hi could you please take a look at the examples in the ref pages?

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_fragment_density_map.html#_examples
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_fragment_density_map2.html#_examples
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_QCOM_fragment_density_map_offset.html#_examples

Unfortunately we don't have samples, however you can look at CTS if you want a working example

https://github.com/KhronosGroup/VK-GL-CTS/blob/main/external/vulkancts/modules/vulkan/renderpass/vktRenderPassFragmentDensityMapTests.cpp

**Comment by SaschaWillems** [comment]
@andywuchuanlong : Did you take a look at our dynamic variable rate shading sample: https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/fragment_shading_rate_dynamic?

**Comment by mnetsch** [comment]
Thanks Sascha, fragment shading rate is indeed an alternate method for performing foveation.

To clarify, on Qualcomm devices our recommendation is to use fragment density map for foveation where possible, especially for fixed foveated rendering to take advantage of the lens characteristics of VR devices. The edges of the lens scatter light more so detailed pixels are needed less. You only need a static density map for this use case which should be applied to all FBO renders for best effect. **Most importantly you can achieve better performance with FDM than FSR due to how our hardware works for most use cases.** VR use cases for FFR require prioritizing speed over quality in the distorted lens regions to meet frame rate.

Fragment shading rate in contrast on our platform gives better quality images by preserving primitive edge pixels and offers more precise and dynamic control of the fragment rates. We recommend developers use this for when apps wish to get performance and power savings for game assets that don't require much detail between adjacent pixels (eg. a blue sky or solid color object). This wont give as good as performance as FDM for us, but developers need precise control if they are doing content based fragment rate reduction and can still see up to 30% performance improvement with little perceivable quality loss if properly tuned.

**Comment by marty-johnson59** [comment]
Hi @mnetsch, thanks for the clarification.  We discussed this on the samples call this week and the group's opinion was that this is too narrow of a use case to prioritize developing a sample ATM.  If you think this is in error, we can bring this up with the Vulkan WG to see if we want to use RFP funded resources to develop this.  LMK - I can drop this on the WG agenda if needed.  Thx

**Comment by marty-johnson59** [comment]
Let's close this as it doesn't seem to be a priority.  Please reopen if this changes.
