### ISSUE TITLE
Use Python for build scripts

### ISSUE THREAD

**Issue by r-kaczynski** [KhronosGroup/Vulkan-Samples#712]
Currently there are 2 different languages used for the build scripts (batch and bash). There are some problems with these languages that Python can solve, for example requiring a script be run from a certain directory for correct behaviour.

**Comment by tomadamatkinson** [comment]
I think we have some which generate samples or build files. These are not used often, generally only once or twice when you want to set up a build. The rest is CMake.

Which scripts do you think will benefit the more being ported to python?

**Comment by gpx1000** [comment]
This is a from me request to make an issue about.  The challenge is in creating the Android build.  If you don't use the specific right directory then it fails.
Consolidating scripts into one seems like a really good idea.  Also, doing a treatment for the last of the major slow things in the CI (the scripted checks) might be good.  I'm also a fan of using one script language everywhere instead of many.  We use Python for the CI and bat/sh for the bldsys.
