### ISSUE TITLE
Doesn't Install, Relative Pathing Not Right, Limited Build Directory

### ISSUE THREAD

**Issue by aWilson41** [KhronosGroup/Vulkan-Samples#823]
I would've expected the app to install & create a self contained package within the install directory (or on linux, install into system if specified). But the app doesn't seem to support install at all. Only spirv-cross shows up in build/install. The actual app seems to reside in build/app/bin.

I'd recommend 
1.) Utilizing cmake install function. Install into build/install/bin. Use add_custom_command to install assets into build/install/bin/assets. Creating an installed packaged, that is also relocatable.
2.) Pass CMAKE_INSTALL_PREFIX into your dependencies so they all install to the same location.
3.) Fix the relative paths on assets so its relative to the binary, not where its run from. Making the app relocatable and basically all build locations valid. (Atm the binary can only run if the build directory is in the src directory). 
4.) Also build instructions say "build\windows\app\bin\Release\AMD64\vulkan_samples.exe", but it appears to be "build\app\bin\Release\AMD64\vulkan_samples.exe"

**Comment by aWilson41** [comment]
As a note/search keyword for anyone finding this. If you run and encounter something like "failed to find roboto font" (the first asset searched for).
1.) Ensure you checked out the submodules as per the instructions
2.) Ensure you cd into the src directory. And run the binary from that specific location. ie: 
```
build\app\bin\Release\AMD64\vulkan_samples.exe
```
cd into build/app/bin/Release/AMD64 and running "vulkan_samples" will not work.

**Comment by tomadamatkinson** [comment]
Hey @aWilson41, we've been discussing using CPack to create an installable version of Vulkan Samples. I've not had chance to look into it but that "should" give the user more control on how the application is installed into their system

You are correct about the asset path issue. Running the project from the source directory has been a requirement since the beginning. I am in agreement that it is very annoying, it seems to trip quite a few people up on the first

Definitely something we should look into
