### ISSUE TITLE
The window might crash if there is the required fonts is not installed on windows.

### ISSUE THREAD

**Issue by Zieng** [KhronosGroup/Vulkan-Samples#980]
![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/9816923/c4aa52f9-e8d0-4b02-8243-8844b01a4558)

It would be better if the framework can fallback to some installed fonts on the machine if we don't find the required font.

**Comment by SaschaWillems** [comment]
We don't use installed fonts. Fonts are loaded from disk. Adding code to fallback to locally installed fonts would be a lot of work.

Your error is caused by running the sample with a wrong working directory. Make sure that the way you run the sample makes sure it can access the assets in the expected path.

**Comment by Zieng** [comment]
Sorry I find it's because I forget to specify the working directory.
Thanks for your quick response!
